"""???

Revision ID: 03ba540d4942
Revises: 2b089526cee0
Create Date: 2025-03-11 17:29:52.017909

"""
from typing import Sequence, Union
import sqlmodel


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03ba540d4942'
down_revision: Union[str, None] = '2b089526cee0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('author', 'full_name')
    op.drop_column('author', 'country')
    op.drop_constraint('book_author_id_fkey', 'book', type_='foreignkey')
    op.drop_column('book', 'year')
    op.drop_column('book', 'description')
    op.drop_column('book', 'title')
    op.drop_column('book', 'author_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('author_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('book', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('book', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('book_author_id_fkey', 'book', 'author', ['author_id'], ['id'])
    op.add_column('author', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('author', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
