"""???

Revision ID: 06850d99c4e4
Revises: 75cd1bb8da62
Create Date: 2025-03-13 12:50:17.372191

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '06850d99c4e4'
down_revision: Union[str, None] = '75cd1bb8da62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
