"""return fields

Revision ID: 30c9db35475d
Revises: 03ba540d4942
Create Date: 2025-03-11 17:44:50.080947

"""
from typing import Sequence, Union
import sqlmodel


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30c9db35475d'
down_revision: Union[str, None] = '03ba540d4942'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('author', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('book', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('book', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('book', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('book', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'book', 'author', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.drop_column('book', 'author_id')
    op.drop_column('book', 'description')
    op.drop_column('book', 'year')
    op.drop_column('book', 'title')
    op.drop_column('author', 'country')
    op.drop_column('author', 'full_name')
    # ### end Alembic commands ###
