"""refactor swaps

Revision ID: 701da5719c56
Revises: 7ea070da3374
Create Date: 2025-03-13 16:23:03.699259

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '701da5719c56'
down_revision: Union[str, None] = '7ea070da3374'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', name='swapstatusenum'), nullable=False),
    sa.Column('initiator_user_id', sa.Integer(), nullable=True),
    sa.Column('initiator_book_id', sa.Integer(), nullable=True),
    sa.Column('responder_user_id', sa.Integer(), nullable=True),
    sa.Column('responder_book_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['initiator_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['responder_book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['responder_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap')
    # ### end Alembic commands ###
