"""add swaps

Revision ID: 75cd1bb8da62
Revises: 965a07c1abe0
Create Date: 2025-03-13 11:17:51.838994

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '75cd1bb8da62'
down_revision: Union[str, None] = '965a07c1abe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('swap',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'CANCELED', name='swapstatusenum'), nullable=False),
    sa.Column('initiator_userbooklink_id', sa.Integer(), nullable=True),
    sa.Column('responder_userbooklink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['initiator_userbooklink_id'], ['userbooklink.id'], ),
    sa.ForeignKeyConstraint(['responder_userbooklink_id'], ['userbooklink.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('swap')
    # ### end Alembic commands ###
