"""make genre.name unique

Revision ID: 7bc3c3a48f66
Revises: 30c9db35475d
Create Date: 2025-03-11 18:20:27.528832

"""
from typing import Sequence, Union
import sqlmodel


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bc3c3a48f66'
down_revision: Union[str, None] = '30c9db35475d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'genre', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'genre', type_='unique')
    # ### end Alembic commands ###
