"""???

Revision ID: 7ea070da3374
Revises: 06850d99c4e4
Create Date: 2025-03-13 16:11:22.822482

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '7ea070da3374'
down_revision: Union[str, None] = '06850d99c4e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
