"""User Book Link

Revision ID: 94698cae6f03
Revises: 7ba7bfc95ffb
Create Date: 2025-03-12 21:32:33.178776

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '94698cae6f03'
down_revision: Union[str, None] = '7ba7bfc95ffb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userbooklink',
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ownership_start_at', sa.DateTime(), nullable=False),
    sa.Column('ownership_end_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('book_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userbooklink')
    # ### end Alembic commands ###
