"""add swaps

Revision ID: 965a07c1abe0
Revises: a7a669b857c6
Create Date: 2025-03-13 11:15:33.683449

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel
from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = '965a07c1abe0'
down_revision: Union[str, None] = 'a7a669b857c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
