"""add nullable to fields

Revision ID: f2c9e41bfa33
Revises: 41c6fe913dcf
Create Date: 2025-03-10 20:57:11.053792

"""
from typing import Sequence, Union
import sqlmodel


from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2c9e41bfa33'
down_revision: Union[str, None] = '41c6fe913dcf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('author', 'country',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('book', 'year',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('author', 'country',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
