site_name: WEB 2.1 Пеньков
nav:
  - Home: index.md
  - ЛР1:
    - ЛР1 и ПР: lab_1/index.md
    - БД: lab_1/db.md
    - api: lab_1/api.md

theme:
  name: material
  palette:
    primary: teal

plugins:
  - render_swagger:
      allow_arbitrary_locations : true
  
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details