"""Fix typo

Revision ID: 1d4ab59a67d6
Revises: e9c3ded348e2
Create Date: 2025-03-10 15:38:49.327563

"""
from typing import Sequence, Union
import sqlmodel

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4ab59a67d6'
down_revision: Union[str, None] = 'e9c3ded348e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('author', 'surnamr')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('surnamr', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('author', 'surname')
    # ### end Alembic commands ###
